baseURL: https://samsonphilipose.netlify.app/
languageCode: en-us
title: Portfolio_website_Samson
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's take a look
    subtitle: |-
      WELCOME! I AM SAMSON. THANKS FOR CLICKING IN. THIS IS A RESPONSIVE SITE TO UNDERSTAND MORE ABOUT ME AND HOW I CAN cONTRIBUTE TO YOUR BUSINESSs.
    title: Hi, my name is Samson Philipose
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Grove End Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: samsonscribe@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: +44 1234567890
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Samson
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/Samsonnsays
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/samson.manoj.37/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/craftimagus/?hl=en-gb
      - icon: fa-github
        label: GitHub
        url: https://github.com/samsonphilipose
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/samsonphil
  image: ''
  name: Samson Philipose
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lego.jfif
        subtitle: A glimpse
        title: About me
        url: blogs/about_me
      - image: galaxy.jpg
        subtitle: A study of sugar and spice
        title: DJIA risk return
        url: blogs/risk_return1
      - image: sunny.jpg
        subtitle: Numbers and numbers
        title: A financial model
        url: blogs/magna
      - image: moon.jpg
        subtitle: Is this kid educated?
        title: My Educational History
        url: blogs/ipsum
      - image: fire.jfif
        subtitle: I have examples, I promise
        title: Leadership and Soft Skills
        url: blogs/ipsum
      - image: water.jfif
        subtitle: What is Samson outside of Finance?
        title: My Hobbies and Extra-curriculars
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "While I am an IB-oriented student who enjoys the occasional FT quip and quantitative model, I have a diversified set of interests.
      \r\n    I enjoy music, art, literary activities and others. \r\n    I also have an art account on instagram which can be found below. \r\n    
      Please feel free to peruse this website and reach out in case of any doubts, collaborations, etc.\r\n Thanks for clicking in."
    title: Feel free to reach out!
    url: blogs
